# Dependabot version updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      next-eslint:
        patterns:
          - next
          - eslint-config-next
      supabase:
        patterns:
          - "@supabase/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
